// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vciibfsxqdulxmfybxol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjaWliZnN4cWR1bHhtZnlieG9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2ODYyMjIsImV4cCI6MjA3NDI2MjIyMn0.2a7ATme7b0aAp3gJVRtq4_-1b7F1FvyKu6qCf36UQBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});