// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aampmpkrrjlbfkgphswq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhbXBtcGtycmpsYmZrZ3Boc3dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1ODA5NDMsImV4cCI6MjA3NDE1Njk0M30.Cdxwo8F_OtXAWFndg_AOBuSl4f6_TTH7dtObykhkqf4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});